### ISSUE TITLE
[Bug] wikipakks page tree inaccessible error

### ISSUE THREAD

**Issue by tojiwdwt** [WikiTransformationProject/wikitraccs-wikipakk-releases#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After migration a few of the main pages became corrupt and were labeled "inaccessible page" I tried republishing in SharePoint but no luck. 
<img width="639" alt="inaccessible page" src="https://github.com/WikiTransformationProject/wikitraccs-releases/assets/155673778/50cb24e7-ab1f-43aa-a3e6-496b7ce98eca">

### Expected Behavior

The title of the page should be correctly labeled, the majority of the pages do work as expected but a few are getting this issue. Please let us know if there is a way to manually fix this in SharePoint.

### WikiTraccs Version

1.10.12

### Confluence Version

Confluence 7 (up to 7.17)

### Confluence Data Center?

- [X] This is about Confluence Data Center

**Comment by heinrich-ulbricht** [comment]
@tojiwdwt Hi, thanks for reporting this.
**Inaccessible page** can mean one of the following:

1. the page does not exist - either it has not been migrated yet, or it has been deleted
1. the currently logged in user account does not have access permissions for this page

Could you please check the **Site Pages** library for a page with ID 1087 and send me a screenshot? You might have to make the columns **ID**, **Confluence: Id**, and **Confluence: Parent Id** columns visible first.

Here's a sample how this will look (the page ID here is 200, it has to be 1087 in your case):

![image](https://github.com/WikiTransformationProject/wikitraccs-wikipakk-releases/assets/3469970/020e10e5-88c5-4073-bbc3-8a32b5f08fe4)

If the page is there, the tree should pick it up and we have to look for reasons why it doesn't. If the page is NOT there, please try to check if this is permission-related, or deletion-related. The behavior would be expected in those cases as the page takes part in a page hierarchy, but is not accessible anymore, for one of the two reasons. We can go on from there.

Thank you.

**Comment by tojiwdwt** [comment]
Hi Heinrich,

Attached is the screenshot. The tree doesn't pick it up, I need to search
for the page by name and it shows up, but now in the expected location of
the page tree.

**Comment by heinrich-ulbricht** [comment]
@tojiwdwt Seems like the image didn't make it to GitHub. Could you please send this via email to support @ wikitransformationproject.com? Thanks.

**Comment by tojiwdwt** [comment]
Hi Heinrich,

I emailed the image per your request. Please let me know if you received it.

Thank you,
Wes

**Comment by heinrich-ulbricht** [comment]
Update: troubleshooting session has been scheduled.

**Comment by heinrich-ulbricht** [comment]
I can reproduce the issue in a test environment. This will be fixed ASAP. Thank you for the opportunity to see it in action.

**Comment by heinrich-ulbricht** [comment]
@tojiwdwt An update has been submitted to App Source that should fix the issue. It's waiting for approval.

**Comment by heinrich-ulbricht** [comment]
@tojiwdwt The adjusted version is now available in App Source. Please update and report back if the issue has been resolved.

https://appsource.microsoft.com/de-de/product/office/WA200005439?tab=Overview

**Comment by tojiwdwt** [comment]
Hi Heinrich,

Sorry for the delayed response. We are testing it out now and will report
back to you.

Thanks,
Wes

**Comment by heinrich-ulbricht** [comment]
This issue should be solved.
